// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqnznurfmcxjisfuzzpa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xbnpudXJmbWN4amlzZnV6enBhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDU4MjksImV4cCI6MjA1MDEyMTgyOX0.8zljvUJW0lEeyxD4czAwHO9lLnhYUwD5fsj-3q-5zAQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);